word_riddles = {
    'abruptly': 'Suddenly and unexpectedly, without warning',
    'absurd': 'Wildly unreasonable or illogical',
    'abyss': 'A deep or seemingly bottomless chasm',
    'affix': 'To attach or fasten something',
    'askew': 'Not in a straight or level position',
    'avenue': 'A wide street or road in a city',
    'awkward': 'Causing difficulty or embarrassment',
    'axiom': 'A statement accepted as true without proof',
    'azure': 'A bright blue color like a clear sky',
    'bagpipes': 'Musical instrument from Scotland',
    'bandwagon': 'A popular trend that attracts followers',
    'banjo': 'Stringed instrument with a circular body',
    'bayou': 'A marshy outlet of a lake or river',
    'beekeeper': 'Someone who maintains colonies of honeybees',
    'bikini': 'A two-piece swimsuit',
    'blitz': 'An intensive or sudden military attack',
    'blizzard': 'A severe snowstorm with high winds',
    'boggle': 'To be astonished or overwhelmed',
    'bookworm': 'A person devoted to reading',
    'boxcar': 'A railroad freight car with a roof',
    'boxful': 'The amount that fills a box',
    'buckaroo': 'A cowboy',
    'buffalo': 'Large wild ox with curved horns',
    'buffoon': 'A ridiculous but amusing person',
    'buxom': 'Having a full, attractive figure',
    'buzzard': 'A large bird of prey',
    'buzzing': 'Making a continuous humming sound',
    'buzzwords': 'Trendy technical jargon',
    'caliph': 'A Muslim ruler',
    'cobweb': 'A spider\'s silken trap',
    'cockiness': 'Arrogant self-confidence',
    'croquet': 'A lawn game with mallets and hoops',
    'crypt': 'An underground room or vault',
    'curacao': 'A blue liqueur or Caribbean island',
    'cycle': 'A series of events that repeat',
    'daiquiri': 'A rum-based cocktail',
    'dirndl': 'A traditional German dress',
    'disavow': 'To deny any responsibility for',
    'dizzying': 'Making you feel unsteady',
    'duplex': 'A house divided into two homes',
    'dwarves': 'Plural of dwarf, small beings in fantasy',
    'embezzle': 'To steal money entrusted to you',
    'equip': 'To supply with necessary items',
    'espionage': 'The practice of spying',
    'euouae': 'A musical mnemonic from medieval times',
    'exodus': 'A mass departure of people',
    'faking': 'Pretending something is real',
    'fishhook': 'A curved tool for catching fish',
    'fixable': 'Capable of being repaired',
    'fjord': 'A narrow inlet between cliffs',
    'flapjack': 'A pancake',
    'flopping': 'Falling or moving heavily',
    'fluffiness': 'The quality of being soft and light',
    'flyby': 'A flight past a point for observation',
    'foxglove': 'A tall plant with purple flowers',
    'frazzled': 'Completely exhausted',
    'frizzled': 'Fried or curled into crisp form',
    'fuchsia': 'A vivid purplish-red color',
    'funny': 'Causing laughter or amusement',
    'gabby': 'Excessively talkative',
    'galaxy': 'A system of millions of stars',
    'galvanize': 'To shock or excite into action',
    'gazebo': 'A small roofed outdoor structure',
    'giaour': 'A non-Muslim, especially Christian',
    'gizmo': 'A gadget or mechanical device',
    'glowworm': 'A beetle larva that glows',
    'glyph': 'A carved symbol or character',
    'gnarly': 'Rough, twisted, or knotted',
    'gnostic': 'Relating to spiritual knowledge',
    'gossip': 'Casual talk about others',
    'grogginess': 'The state of being dazed',
    'haiku': 'A Japanese poem with 5-7-5 syllables',
    'haphazard': 'Lacking order or planning',
    'hyphen': 'A punctuation mark connecting words',
    'iatrogenic': 'Caused by medical treatment',
    'icebox': 'An old-fashioned refrigerator',
    'injury': 'Physical harm or damage',
    'ivory': 'Hard white material from tusks',
    'ivy': 'A climbing evergreen plant',
    'jackpot': 'A large cash prize',
    'jaundice': 'A condition causing yellow skin',
    'jawbreaker': 'A very hard round candy',
    'jaywalk': 'To cross a street illegally',
    'jazziest': 'Most lively and energetic',
    'jazzy': 'Bright, colorful, and eye-catching',
    'jelly': 'A sweet spread made from fruit',
    'jigsaw': 'A puzzle with interlocking pieces',
    'jinx': 'A curse or spell of bad luck',
    'jiujitsu': 'A Japanese martial art',
    'jockey': 'A person who rides horses in races',
    'jogging': 'Running at a steady gentle pace',
    'joking': 'Making humorous remarks',
    'jovial': 'Cheerful and friendly',
    'joyful': 'Feeling great happiness',
    'juicy': 'Full of juice or moisture',
    'jukebox': 'A coin-operated music player',
    'jumbo': 'Very large in size',
    'kayak': 'A narrow canoe propelled by paddle',
    'kazoo': 'A simple musical instrument that hums',
    'keyhole': 'The hole where a key is inserted',
    'khaki': 'A dull yellowish-brown color',
    'kilobyte': 'A unit of computer memory',
    'kiosk': 'A small open-fronted booth',
    'kitsch': 'Art that is garish or overly sentimental',
    'kiwifruit': 'A fuzzy brown fruit with green flesh',
    'klutz': 'A clumsy person',
    'knapsack': 'A backpack or rucksack',
    'larynx': 'The voice box in your throat',
    'lengths': 'Measurements of distance',
    'lucky': 'Having good fortune',
    'luxury': 'A state of great comfort',
    'lymph': 'A clear fluid in body tissues',
    'marquis': 'A nobleman ranking above a count',
    'matrix': 'An array of numbers or elements',
    'megahertz': 'A unit of frequency',
    'microwave': 'An appliance that heats food quickly',
    'mnemonic': 'A memory aid or pattern',
    'mystify': 'To puzzle or bewilder',
    'naphtha': 'A flammable oil or solvent',
    'nightclub': 'A venue for entertainment at night',
    'nowadays': 'In the present time',
    'numbskull': 'A stupid or foolish person',
    'nymph': 'A mythological spirit of nature',
    'onyx': 'A semi-precious black stone',
    'ovary': 'A female reproductive organ',
    'oxidize': 'To combine with oxygen',
    'oxygen': 'A gas essential for life',
    'pajama': 'Loose clothing for sleeping',
    'peekaboo': 'A game played with babies',
    'phlegm': 'Thick mucus in the respiratory tract',
    'pixel': 'The smallest element of a digital image',
    'pizazz': 'Attractive style or flair',
    'pneumonia': 'An inflammatory lung disease',
    'polka': 'A lively dance from Bohemia',
    'pshaw': 'An exclamation of contempt',
    'psyche': 'The human soul or mind',
    'puppy': 'A young dog',
    'puzzling': 'Confusing or difficult to understand',
    'quartz': 'A hard crystalline mineral',
    'queue': 'A line of people waiting',
    'quips': 'Witty or clever remarks',
    'quixotic': 'Exceedingly idealistic and unrealistic',
    'quiz': 'A short test of knowledge',
    'quizzes': 'Multiple tests of knowledge',
    'quorum': 'The minimum number needed for a meeting',
    'razzmatazz': 'Noisy or showy activity',
    'rhubarb': 'A plant with edible pink stalks',
    'rhythm': 'A strong, regular repeated pattern',
    'rickshaw': 'A two-wheeled passenger vehicle',
    'schnapps': 'A strong alcoholic drink',
    'scratch': 'To scrape with nails or claws',
    'shiv': 'A knife used as a weapon',
    'snazzy': 'Stylish and fashionable',
    'sphinx': 'An Egyptian monument with a lion\'s body',
    'spritz': 'To spray liquid in small drops',
    'squawk': 'A loud harsh cry',
    'staff': 'A group of employees',
    'strength': 'The quality of being strong',
    'strengths': 'Qualities of being strong',
    'stretch': 'To extend or lengthen',
    'stronghold': 'A place of security or survival',
    'stymied': 'Prevented or blocked',
    'subway': 'An underground railway system',
    'swivel': 'To turn around a point',
    'syndrome': 'A group of symptoms',
    'thriftless': 'Spending money carelessly',
    'thumbscrew': 'An instrument of torture',
    'topaz': 'A yellow precious stone',
    'transcript': 'A written or printed record',
    'transgress': 'To go beyond the limits',
    'transplant': 'To move from one place to another',
    'triphthong': 'Three vowels in one syllable',
    'twelfth': 'Number 12 in sequence',
    'twelfths': 'Plural of twelfth',
    'unknown': 'Not known or familiar',
    'unworthy': 'Not deserving respect',
    'unzip': 'To open a zipper',
    'uptown': 'The residential part of a city',
    'vaporize': 'To convert into vapor',
    'vixen': 'A female fox',
    'vodka': 'A clear Russian alcoholic spirit',
    'voodoo': 'A religion involving magic',
    'vortex': 'A whirling mass of water or air',
    'voyeurism': 'The practice of spying on people',
    'walkway': 'A passage for walking',
    'waltz': 'A ballroom dance in triple time',
    'wave': 'A moving ridge on water surface',
    'wavy': 'Having a series of curves',
    'waxy': 'Resembling wax in texture',
    'wellspring': 'An original source of something',
    'wheezy': 'Breathing with difficulty',
    'whiskey': 'A strong alcoholic spirit',
    'whizzing': 'Moving quickly through the air',
    'whomever': 'Whatever person',
    'wimpy': 'Weak and cowardly',
    'witchcraft': 'The practice of magic',
    'wizard': 'A person with magical powers',
    'woozy': 'Dizzy and unsteady',
    'wristwatch': 'A watch worn on the wrist',
    'wyvern': 'A winged dragon with two legs',
    'xylophone': 'A musical instrument with wooden bars',
    'yachtsman': 'A person who sails yachts',
    'yippee': 'An exclamation of excitement',
    'yoked': 'Joined together',
    'youthful': 'Having the characteristics of youth',
    'yummy': 'Delicious',
    'zephyr': 'A gentle mild breeze',
    'zigzag': 'A pattern with sharp turns',
    'zigzagging': 'Moving in a zigzag pattern',
    'zilch': 'Nothing at all',
    'zipper': 'A fastening device with interlocking teeth',
    'zodiac': 'A circle of twelve astrological signs',
    'zombie': 'An undead creature',
}
